### ISSUE TITLE
emailの一意性のバリデーションについて

### ISSUE THREAD

**Issue by muraken-ken** [yasslab/sample_apps#54]
第6章でUserモデルのemail属性の一意性についてバリデーションしています。
現状のプログラムでは「同じ文字列で大文字が混じったemail」を新規登録するとバリデーションをすり抜け、DB登録時に一意性のエラーになると思います。
emailのバリデーションを`uniqueness: { case_sensitive: false }`にするか、
コールバックを`before_save { self.email = email.downcase }`を`before_validation`するか
の対応が必要だと思います。

**Comment by yasulab** [comment]
なるほど...! 自分が勘違いしていたみたいですね 😂 細かな再現方法のコメントありがとうございます! (＞人＜ )💖 手元でも確認してみます! 👀💨✨

**Comment by yasulab** [comment]
手元で再現して同じ現象（バリデーションをすり抜けてしまうこと）を確認しました! バリデーションでキャッチできた方がユーザー視点では親切だと思うので、ご提案していただいた

> `uniqueness: true` を `uniqueness: { case_sensitive: false }` にする

という方法で対応していきますね! 改めて、フィードバックりがとうございます...!! 🙏 ✨ 

![image](https://user-images.githubusercontent.com/155807/137244630-82c49aa6-d187-4e4e-b685-ea0b03019b88.png)
