### ISSUE TITLE
sample_apps から３桁目のバージョンを消す

### ISSUE THREAD

**Issue by rakuda-san-desu** [yasslab/sample_apps#57]
現状だとパッチバージョンの変更をおこなった場合、フォルダ名も変更することになる。
👉 対応するURLも変わってしまう

### やりたいこと
sample_apps から３桁目のバージョンを消す

🔽 変更例
```diff
- 6_0_0
+ 6_0
```

🔽 参考
![image](https://user-images.githubusercontent.com/41533420/143194021-98cdc956-ffe4-455b-8294-ce4dcb45059d.png)

**Comment by himajin315** [comment]
消えてました
<img width="281" alt="スクリーンショット 2021-12-17 12 16 00" src="https://user-images.githubusercontent.com/1221303/146483258-bfbc5da8-5873-4c60-972e-db6cb548c7cd.png">
