### ISSUE TITLE
.gitignoreが存在しないディレクトリにゴミファイルが存在する

### ISSUE THREAD

**Issue by JunichiIto** [yasslab/sample_apps#6]
.gitignoreがないディレクトリがいくつかあります。そうしたディレクトリはlogファイルやcacheファイルのような不要なファイルが残ったままになっています。

```
$ find . -name "*.log"
./5_0_0_1/ch13/log/development.log
./5_0_0_1/ch13/log/test.log
./5_1_2/ch14/log/development.log
./omake/ch12_4_0/log/development.log
./omake/ch12_4_0/log/test.log
```

自分で修正用のpull reqを作ることも考えましたが、ファイルの要・不要をきちんと識別できる自信がなかったため（実はテキスト内の説明で使っているとか）、issueの投稿のみとさせてもらいました（すいません）。

**Comment by yasulab** [comment]
報告ありがとうございます！テキストでは使っていないので、これらは消しても大丈夫ですね :)
