### ISSUE TITLE
14章のUnfollowボタンのレイアウトがキャプチャと異なる

### ISSUE THREAD

**Issue by tunepolo** [yasslab/sample_apps#8]
下記のTeratail質問と同じ現象に遭遇しました。

- [Railsチュートリアル 14章　Unfollowボタンが表示されない](https://teratail.com/questions/147020)

このリポジトリのサンプル 5_1_2/ch14 を動かしてもボタンに灰色の背景が付いていません。
コードかキャプチャかどちらかが間違っているのではないでしょうか?

確認は"Google Chrome バージョン: 71.0.3578.98（Official Build） （64 ビット）"で行いました。

サンプルコードで用いているgemの'bootstrap-sass'はBootstrap3系に対応しているようですが、ボタンのスタイルを見てもキャプチャと類似するものはありません。

https://getbootstrap.com/docs/3.3/css/#buttons

**Comment by yasulab** [comment]
ご指摘ありがとうございます! こちら見逃してました (＞人＜ )💦
手元の環境で確認した限りでは、問題なく動いているようでした :eyes: ✅
(Bootstrap のマイナーバージョン以下で挙動が異なるのかもしれないですね 🤔💭)

![image](https://user-images.githubusercontent.com/155807/137252157-f5fd4113-81fa-4137-a18c-7016a9024213.png)

とはいえ `btn-default` を追加しても大きく挙動が変わることはなかったので、Bootstrap の細かなバージョン差異が影響しているケースも鑑みて、念のためコードの方にも下記のとおり `btn-default` クラスを追加しておきました! 🛠💨

![image](https://user-images.githubusercontent.com/155807/137253023-43b152af-aaa5-455f-89bb-050b26f15ce9.png)

フィードバックありがとうございます...!! (＞人＜ )✨
